# Generated by Django 5.2.5 on 2025-09-04 17:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='poster'),
        ),
    ]
